services:
  - type: web
    name: fashionstore-be
    env: php
    plan: free
    region: oregon
    rootDir: FashionStore_BE
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: APP_KEY
        generateValue: true
